services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: tprod
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
